name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  specs:
    name: specs
    # runs-on: actuated-arm64-2cpu-8gb
    runs-on: actuated-2cpu-8gb
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Check specs
        run: |
          ./specs.sh

  test:
    name: test
    runs-on: actuated-2cpu-2gb
    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          driver-opts: network=host
          install: true
          version: v0.9.1

      - name: Test kvm
        run: ls -l /dev/kvm
